// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lZ3Po28qt8JIaD4w_GJdgovseBcZyUw',
    appId: '1:33008958055:web:9687db15b7f2db096832c2',
    messagingSenderId: '33008958055',
    projectId: 'plancation-74a7a',
    authDomain: 'plancation-74a7a.firebaseapp.com',
    storageBucket: 'plancation-74a7a.appspot.com',
    measurementId: 'G-L9MMEXN7ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdevZZhsnAtqoJesH3Y8b0-4jOI-S7po',
    appId: '1:33008958055:android:7f1d046579979c276832c2',
    messagingSenderId: '33008958055',
    projectId: 'plancation-74a7a',
    storageBucket: 'plancation-74a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19JGC7-CiKFE7N_ZMAoGx848c7TJ4740',
    appId: '1:33008958055:ios:3fba4f56845725d86832c2',
    messagingSenderId: '33008958055',
    projectId: 'plancation-74a7a',
    storageBucket: 'plancation-74a7a.appspot.com',
    iosClientId: '33008958055-hd9hr2lpqis7s5t1pco1bvl0ojsa60fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.plancation',
  );
}
